//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.01.13 at 09:08:41 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.com/exercises/transfersystem/transfer-request-response.xsd")
package com.example.exercises.transfersystem.transfer_request_response;
