//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0
// See https://eclipse-ee4j.github.io/jaxb-ri
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.01.13 at 08:59:27 AM CET
//


package com.example.exercises.transfersystem.transfer_request_response;

import java.math.BigDecimal;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for TransferResponseType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="TransferResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TargetAccountNumber" type="{http://www.example.com/exercises/transfersystem/transfer-request-response.xsd}AccountNumberType"/&gt;
 *         &lt;element name="Action" type="{http://www.example.com/exercises/transfersystem/transfer-request-response.xsd}ActionType"/&gt;
 *         &lt;element name="Currency" type="{http://www.example.com/exercises/transfersystem/transfer-request-response.xsd}CurrencyType"/&gt;
 *         &lt;element name="Quantity" type="{http://www.example.com/exercises/transfersystem/transfer-request-response.xsd}NonNegativeDecimal"/&gt;
 *         &lt;element name="Outcome" type="{http://www.example.com/exercises/transfersystem/transfer-request-response.xsd}OutcomeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(name = "TransferResponse")
@XmlType(name = "TransferResponseType", propOrder = {
    "requestId",
    "targetAccountNumber",
    "action",
    "currency",
    "quantity",
    "outcome"
})
public class TransferResponseType {

    @XmlElement(name = "RequestId", required = true)
    protected String requestId;
    @XmlElement(name = "TargetAccountNumber", required = true)
    protected String targetAccountNumber;
    @XmlElement(name = "Action", required = true)
    @XmlSchemaType(name = "string")
    protected ActionType action;
    @XmlElement(name = "Currency", required = true)
    protected String currency;
    @XmlElement(name = "Quantity", required = true)
    protected BigDecimal quantity;
    @XmlElement(name = "Outcome", required = true)
    @XmlSchemaType(name = "string")
    protected OutcomeType outcome;

    /**
     * Gets the value of the requestId property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setRequestId(String value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the targetAccountNumber property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getTargetAccountNumber() {
        return targetAccountNumber;
    }

    /**
     * Sets the value of the targetAccountNumber property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setTargetAccountNumber(String value) {
        this.targetAccountNumber = value;
    }

    /**
     * Gets the value of the action property.
     *
     * @return
     *     possible object is
     *     {@link ActionType }
     *
     */
    public ActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     *
     * @param value
     *     allowed object is
     *     {@link ActionType }
     *
     */
    public void setAction(ActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the currency property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCurrency(String value) {
        this.currency = value;
    }

    /**
     * Gets the value of the quantity property.
     *
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *
     */
    public BigDecimal getQuantity() {
        return quantity;
    }

    /**
     * Sets the value of the quantity property.
     *
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *
     */
    public void setQuantity(BigDecimal value) {
        this.quantity = value;
    }

    /**
     * Gets the value of the outcome property.
     *
     * @return
     *     possible object is
     *     {@link OutcomeType }
     *
     */
    public OutcomeType getOutcome() {
        return outcome;
    }

    /**
     * Sets the value of the outcome property.
     *
     * @param value
     *     allowed object is
     *     {@link OutcomeType }
     *
     */
    public void setOutcome(OutcomeType value) {
        this.outcome = value;
    }

}
